config/routes.rb
SupplySide::Application.routes.draw do
  
  resources :password_resets   
  resources :sessions
  resources :users
  
  match "/logout" => "sessions#destroy"
  match "/login" => "sessions#new"
  match "/recover" => "password_resets#new"
  match "/signup" => "users#new"
  match "/secret" => "pages#secret"

  root :to => "pages#home"
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description
  
  belongs_to :user
  
  validates_presence_of :user_id
  validates_presence_of :name
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_presence_of :email
  validates_uniqueness_of :email, :case_sensitive => false
  validates_format_of :email, :with => valid_email_regex
  
  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  def not_authenticated
    redirect_to login_url, :alert => "First log in to view this page."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  protect_from_forgery
  before_filter :require_login, :only => :secret
  
  def home
  end
  
  def secret
  end
  
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    # request password reset.
    # you get here when the user entered his email in the reset password form and submitted it.
    @user = User.find_by_email(params[:email])
    
    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user
    
    redirect_to root_url, :notice => "Email sent with password reset instructions."
  end
  
  # This is the reset password form.
  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]
    not_authenticated unless @user
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:token]
    @user = User.load_from_reset_password_token(params[:token])
    not_authenticated unless @user
    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid."
    end
  end
  
  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def app_name
    'Supply Side'
  end

  def app_domain
    'gosupplyside.com'
  end

  def system_email
    'leemcalilly@gmail.com'
  end
    
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "#{app_name}"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="user_nav">
    <% if current_user %>
      <p>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log out", logout_path %>
      </p>
    <% else %>
      <p>
        <%= link_to "Sign up", signup_path %> or
        <%= link_to "Log in", login_path  %>.
      </p>
    <% end %>
  </div>
  
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>

<h1><%= app_name %></h1>

<p>A tool for managing your supply chain.</p>

<p><%= link_to "Visit the secret page", secret_path %>.</p>

app/views/pages/secret.html.erb
<% provide(:title, 'Secret') %>

<h1>Secret</h1>

<p>Listen, do you want to know a secret?</p>

<p><%= link_to "Return Home", root_path %></p>

app/views/password_resets/_form.html.erb
<%= form_for @user, :url => password_reset_path(@user), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <fieldset>
    <%= f.label :email %><br />
    <%= @user.email %>
  </fieldset>
  
  <fieldset>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </fieldset>
  
  <fieldset>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
    <%= hidden_field_tag :token, @token %>
  </fieldset>
  
  <fieldset>
    <%= f.submit %>
  </fieldset>
<% end %>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= render 'form' %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <fieldset>
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </fieldset>
  
  <fieldset>
    <%= submit_tag "Reset Password" %>
  </fieldset>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <fieldset>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </fieldset>
  
  <fieldset>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </fieldset>
  
  <fieldset>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </fieldset>
  
  <fieldset>
    <%= f.submit "Sign Up" %>
  </fieldset>
<% end %>